name: Android Artifact Publish

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for inji-vc-client Updates'
        type: string
  push:
    branches:
    - develop
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop

jobs:
  maven-publish:
    uses: mosip/kattu/.github/workflows/maven-publish-android.yml@master
    with:
      SERVICE_LOCATION: '.'
      ANDROID_SERVICE_LOCATION: 'kotlin'
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{secrets.OSSRH_SNAPSHOT_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}